version: "2"
linters:
  enable:
    - gocritic
    - misspell
    - mnd
    - nlreturn
    - perfsprint
    - predeclared
    - staticcheck
    - testifylint
    - thelper
    - usestdlibvars
    - whitespace
  settings:
    nlreturn:
      block-size: 2
    testifylint:
      disable:
        - require-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
