default_stages: ["pre-commit", "pre-push"]
default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        entry: "mypy --strict ./python"
        pass_filenames: false
        additional_dependencies:
          - "pytest-asyncio"
          - "pydantic"
          - "marimo"
  - repo: local
    hooks:
      - id: pytest-check
        stages: [pre-push]
        types: [python]
        name: pytest-check
        entry: python -m pytest -v python/tests/
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: system
        stages: [pre-commit, pre-push]
        entry: bash -c 'golangci-lint run --allow-parallel-runners'
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: gofumpt
  - repo: local
    hooks:
      - id: go-test
        stages: [pre-push]
        name: go test
        entry: bash -c 'if command -v gotestsum; then gotestsum; else go test ./...; fi'
        language: system
        pass_filenames: false
        always_run: true