# .readthedocs.yaml
version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev  # Install dev dependencies as well
