site_name: Numerous SDK documentation

nav:
  - Home: README.md
  - Website: https://numerous.com
  - GitHub page: https://github.com/numerous-com/numerous-sdk
  - PyPI page: https://pypi.org/project/numerous/
  - Platform docs: https://numerous.com/docs
  - Usage:
    - Collections: collections.md
    - Collection documents: collection_documents.md
    - Collection files: collection_files.md
    - Sessions: sessions.md
    - Users: user.md
    - Frameworks: frameworks.md
  - API reference: reference/

theme:
  name: material
  logo: logo.svg
  features:
      - content.code.copy

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
