site_name: Numerous SDK documentation
nav:
  - Home: README.md
  - Website: https://numerous.com
  - GitHub Page: https://github.com/numerous-com/numerous-sdk
  - PyPI Page: https://pypi.org/project/numerous/
  - Platform Docs: https://numerous.com/docs
  - API Reference:
    - Collections: collections.md
    - Sessions: sessions.md
    - Users: user.md
    - Frameworks: frameworks.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences