# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionFileReference


class CollectionFileCreate(BaseModel):
    collection_file_create: Union[
        "CollectionFileCreateCollectionFileCreateCollectionFile",
        "CollectionFileCreateCollectionFileCreateCollectionNotFound",
    ] = Field(alias="collectionFileCreate", discriminator="typename__")


class CollectionFileCreateCollectionFileCreateCollectionFile(CollectionFileReference):
    typename__: Literal["CollectionFile"] = Field(alias="__typename")


class CollectionFileCreateCollectionFileCreateCollectionNotFound(BaseModel):
    typename__: Literal["CollectionNotFound"] = Field(alias="__typename")


CollectionFileCreate.model_rebuild()
