# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionDocumentReference


class CollectionDocumentTagDelete(BaseModel):
    collection_document_tag_delete: Union[
        "CollectionDocumentTagDeleteCollectionDocumentTagDeleteCollectionDocument",
        "CollectionDocumentTagDeleteCollectionDocumentTagDeleteCollectionDocumentNotFound",
    ] = Field(alias="collectionDocumentTagDelete", discriminator="typename__")


class CollectionDocumentTagDeleteCollectionDocumentTagDeleteCollectionDocument(
    CollectionDocumentReference
):
    typename__: Literal["CollectionDocument"] = Field(alias="__typename")


class CollectionDocumentTagDeleteCollectionDocumentTagDeleteCollectionDocumentNotFound(
    BaseModel
):
    typename__: Literal["CollectionDocumentNotFound"] = Field(alias="__typename")


CollectionDocumentTagDelete.model_rebuild()
