# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionNotFound, CollectionReference


class CollectionTagAdd(BaseModel):
    collection_tag_add: Union[
        "CollectionTagAddCollectionTagAddCollection",
        "CollectionTagAddCollectionTagAddCollectionNotFound",
    ] = Field(alias="collectionTagAdd", discriminator="typename__")


class CollectionTagAddCollectionTagAddCollection(CollectionReference):
    typename__: Literal["Collection"] = Field(alias="__typename")


class CollectionTagAddCollectionTagAddCollectionNotFound(CollectionNotFound):
    typename__: Literal["CollectionNotFound"] = Field(alias="__typename")


CollectionTagAdd.model_rebuild()
