# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionNotFound, CollectionReference


class CollectionTagDelete(BaseModel):
    collection_tag_delete: Union[
        "CollectionTagDeleteCollectionTagDeleteCollection",
        "CollectionTagDeleteCollectionTagDeleteCollectionNotFound",
    ] = Field(alias="collectionTagDelete", discriminator="typename__")


class CollectionTagDeleteCollectionTagDeleteCollection(CollectionReference):
    typename__: Literal["Collection"] = Field(alias="__typename")


class CollectionTagDeleteCollectionTagDeleteCollectionNotFound(CollectionNotFound):
    typename__: Literal["CollectionNotFound"] = Field(alias="__typename")


CollectionTagDelete.model_rebuild()
