# Generated by ariadne-codegen
# Source: queries.gql

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionNotFound, CollectionWithTags


class CollectionTags(BaseModel):
    collection: Optional[
        Annotated[
            Union[
                "CollectionTagsCollectionCollection",
                "CollectionTagsCollectionCollectionNotFound",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class CollectionTagsCollectionCollection(CollectionWithTags):
    typename__: Literal["Collection"] = Field(alias="__typename")


class CollectionTagsCollectionCollectionNotFound(CollectionNotFound):
    typename__: Literal["CollectionNotFound"] = Field(alias="__typename")


CollectionTags.model_rebuild()
