# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import CollectionDocumentReference


class CollectionDocumentDelete(BaseModel):
    collection_document_delete: Union[
        "CollectionDocumentDeleteCollectionDocumentDeleteCollectionDocument",
        "CollectionDocumentDeleteCollectionDocumentDeleteCollectionDocumentNotFound",
    ] = Field(alias="collectionDocumentDelete", discriminator="typename__")


class CollectionDocumentDeleteCollectionDocumentDeleteCollectionDocument(
    CollectionDocumentReference
):
    typename__: Literal["CollectionDocument"] = Field(alias="__typename")


class CollectionDocumentDeleteCollectionDocumentDeleteCollectionDocumentNotFound(
    BaseModel
):
    typename__: Literal["CollectionDocumentNotFound"] = Field(alias="__typename")


CollectionDocumentDelete.model_rebuild()
