# Generated by ariadne-codegen
# Source: queries.gql

from typing import List

from .base_model import BaseModel


class DeploymentTasks(BaseModel):
    tasks: List["DeploymentTasksTasks"]


class DeploymentTasksTasks(BaseModel):
    id: str
    command: List[str]


DeploymentTasks.model_rebuild()
