# Generated by ariadne-codegen
# Source: queries.gql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class CollectionDocumentReference(BaseModel):
    id: str
    key: str


class CollectionDocumentWithData(BaseModel):
    id: str
    key: str
    data: Any
    tags: List["CollectionDocumentWithDataTags"]


class CollectionDocumentWithDataTags(BaseModel):
    key: str
    value: str


class CollectionFileNotFound(BaseModel):
    id: str


class CollectionFileReference(BaseModel):
    id: str
    key: str
    download_url: Optional[str] = Field(alias="downloadURL")
    upload_url: Optional[str] = Field(alias="uploadURL")
    tags: List["CollectionFileReferenceTags"]


class CollectionFileReferenceTags(BaseModel):
    key: str
    value: str


class CollectionNotFound(BaseModel):
    id: str


class CollectionOrganizationMismatch(BaseModel):
    parent_id: str = Field(alias="parentID")
    parent_organization_id: str = Field(alias="parentOrganizationID")
    requested_organization_id: str = Field(alias="requestedOrganizationID")


class CollectionReference(BaseModel):
    id: str
    key: str


class CollectionWithTags(BaseModel):
    id: str
    key: str
    tags: List["CollectionWithTagsTags"]


class CollectionWithTagsTags(BaseModel):
    key: str
    value: str


CollectionDocumentReference.model_rebuild()
CollectionDocumentWithData.model_rebuild()
CollectionFileNotFound.model_rebuild()
CollectionFileReference.model_rebuild()
CollectionNotFound.model_rebuild()
CollectionOrganizationMismatch.model_rebuild()
CollectionReference.model_rebuild()
CollectionWithTags.model_rebuild()
