# Generated by ariadne-codegen
# Source: queries.gql

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel


class OrganizationByID(BaseModel):
    organization_by_id: Union[
        "OrganizationByIDOrganizationByIdOrganization",
        "OrganizationByIDOrganizationByIdOrganizationNotFound",
    ] = Field(alias="organizationById", discriminator="typename__")


class OrganizationByIDOrganizationByIdOrganization(BaseModel):
    typename__: Literal["Organization"] = Field(alias="__typename")
    id: str
    slug: str


class OrganizationByIDOrganizationByIdOrganizationNotFound(BaseModel):
    typename__: Literal["OrganizationNotFound"] = Field(alias="__typename")


OrganizationByID.model_rebuild()
