# Generated by ariadne-codegen
# Source: queries.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import TaskInstanceData


class TaskInstance(BaseModel):
    task_instance: Optional["TaskInstanceTaskInstance"] = Field(alias="taskInstance")


class TaskInstanceTaskInstance(TaskInstanceData):
    pass


TaskInstance.model_rebuild()
