# Generated by ariadne-codegen
# Source: queries.gql

from typing import List

from pydantic import Field

from .base_model import BaseModel
from .fragments import TaskInstanceData


class TaskInstances(BaseModel):
    task_instances: List["TaskInstancesTaskInstances"] = Field(alias="taskInstances")


class TaskInstancesTaskInstances(TaskInstanceData):
    pass


TaskInstances.model_rebuild()
