# Generated by ariadne-codegen
# Source: queries.gql

from pydantic import Field

from .base_model import BaseModel


class TaskInstanceUpdateProgress(BaseModel):
    task_instance_update_progress: (
        "TaskInstanceUpdateProgressTaskInstanceUpdateProgress"
    ) = Field(alias="taskInstanceUpdateProgress")


class TaskInstanceUpdateProgressTaskInstanceUpdateProgress(BaseModel):
    id: str


TaskInstanceUpdateProgress.model_rebuild()
