# Generated by ariadne-codegen
# Source: queries.gql

from pydantic import Field

from .base_model import BaseModel


class TaskInstanceSetOutput(BaseModel):
    task_instance_set_output: "TaskInstanceSetOutputTaskInstanceSetOutput" = Field(
        alias="taskInstanceSetOutput"
    )


class TaskInstanceSetOutputTaskInstanceSetOutput(BaseModel):
    id: str


TaskInstanceSetOutput.model_rebuild()
