# Generated by ariadne-codegen
# Source: queries.gql

from pydantic import Field

from .base_model import BaseModel


class TaskStart(BaseModel):
    task_start: "TaskStartTaskStart" = Field(alias="taskStart")


class TaskStartTaskStart(BaseModel):
    id: str


TaskStart.model_rebuild()
