# Generated by ariadne-codegen
# Source: queries.gql

from pydantic import Field

from .base_model import BaseModel


class TaskStop(BaseModel):
    task_stop: "TaskStopTaskStop" = Field(alias="taskStop")


class TaskStopTaskStop(BaseModel):
    task_instance_id: str = Field(alias="taskInstanceID")


TaskStop.model_rebuild()
