fragment ButtonValue on Button {
  buttonValue: value
}

fragment TextFieldValue on TextField {
  textValue: value
}

fragment NumberFieldValue on NumberField {
  numberValue: value
}

fragment SliderValue on SliderElement {
  sliderValue: value
  minValue
  maxValue
}

fragment HTMLValue on HTMLElement {
  html
}

fragment GraphContext on ElementGraphContext {
  parent {
    __typename
    id
  }
  affectedBy {
    id
  }
  affects {
    id
  }
}

query AllElements($toolSessionId: ID!) {
  session: toolSession(id: $toolSessionId) {
    id
    clientID
    all: allElements {
      id
      name
      graphContext {
        ...GraphContext
      }
      ...ButtonValue
      ...TextFieldValue
      ...NumberFieldValue
      ...HTMLValue
      ...SliderValue
    }
  }
}

mutation UpdateElement(
  $sessionID: ID!
  $clientID: ID!
  $element: ElementInput!
) {
  elementUpdate(
    toolSessionId: $sessionID
    clientId: $clientID
    element: $element
  ) {
    __typename
  }
}

subscription Updates($sessionId: ID!, $clientId: ID!) {
  toolSessionEvent(toolSessionId: $sessionId, clientId: $clientId) {
    __typename
    ... on ToolSessionElementUpdated {
      element {
        id
        name
        graphContext {
          ...GraphContext
        }
        ...ButtonValue
        ...TextFieldValue
        ...NumberFieldValue
        ...HTMLValue
        ...SliderValue
      }
    }
    ... on ToolSessionActionTriggered {
      element {
        id
        name
      }
    }
  }
}

fragment CollectionReference on Collection {
  id
  key
}

fragment CollectionDocumentReference on CollectionDocument {
  id
  key
  data
  tags {
    key
    value
  }
}

fragment CollectionNotFound on CollectionNotFound {
  id
}

mutation CollectionCreate($organizationID: ID!, $key: ID!, $parentID: ID) {
  collectionCreate(
    organizationID: $organizationID
    key: $key
    parentID: $parentID
  ) {
    __typename
    ... on Collection {
      ...CollectionReference
    }
    ... on CollectionNotFound {
      ...CollectionNotFound
    }
  }
}

mutation CollectionCollections(
  $organizationID: ID!
  $key: ID!
  $after: ID
  $first: Int
) {
  collectionCreate(organizationID: $organizationID, key: $key) {
    __typename
    ... on Collection {
      id
      key
      collections(after: $after, first: $first) {
        edges {
          node {
            ... on Collection {
              ...CollectionReference
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}

mutation CollectionDocument($organizationID: ID!, $key: ID!, $docKey: ID!) {
  collectionCreate(organizationID: $organizationID, key: $key) {
    __typename
    ... on Collection {
      document(key: $docKey) {
        __typename
        ... on CollectionDocument {
          ...CollectionDocumentReference
        }
      }
    }
  }
}

mutation collectionDocumentSet(
  $collectionID: ID!
  $key: ID!
  $data: Base64JSON!
) {
  collectionDocumentSet(collectionID: $collectionID, key: $key, data: $data) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation collectionDocumentDelete($id: ID!) {
  collectionDocumentDelete(id: $id) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation collectionDocumentTagAdd($id: ID!, $tag: TagInput!) {
  collectionDocumentTagAdd(id: $id, tag: $tag) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation collectionDocumentTagDelete($id: ID!, $tag_key: String!) {
  collectionDocumentTagDelete(id: $id, key: $tag_key) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation collectionDocuments(
  $organizationID: ID!
  $key: ID!
  $tag: TagInput
  $after: ID
  $first: Int
) {
  collectionCreate(organizationID: $organizationID, key: $key) {
    __typename
    ... on Collection {
      id
      key
      documents(after: $after, first: $first, tag: $tag) {
        edges {
          node {
            __typename
            ... on CollectionDocument {
              ...CollectionDocumentReference
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}
