fragment CollectionReference on Collection {
  id
  key
}

fragment CollectionDocumentReference on CollectionDocument {
  id
  key
  data
  tags {
    key
    value
  }
}

fragment CollectionNotFound on CollectionNotFound {
  id
}

fragment CollectionFileReference on CollectionFile {
  id
  key
  downloadURL
  uploadURL
  tags {
    key
    value
  }
}

mutation CollectionCreate($organizationID: ID!, $key: ID!, $parentID: ID) {
  collectionCreate(
    organizationID: $organizationID
    key: $key
    parentID: $parentID
  ) {
    __typename
    ... on Collection {
      ...CollectionReference
    }
    ... on CollectionNotFound {
      ...CollectionNotFound
    }
  }
}

query CollectionCollections(
  $collectionID: ID!
  $after: ID
  $first: Int
) {
  collection(id: $collectionID) {
    __typename
    ... on Collection {
      id
      key
      collections(after: $after, first: $first) {
        edges {
          node {
            ... on Collection {
              ...CollectionReference
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}

query CollectionDocument($collectionID: ID!, $docKey: ID!) {
  collection(id: $collectionID) {
    __typename
    ... on Collection {
      document(key: $docKey) {
        __typename
        ... on CollectionDocument {
          ...CollectionDocumentReference
        }
      }
    }
  }
}

mutation CollectionDocumentSet(
  $collectionID: ID!
  $key: ID!
  $data: Base64JSON!
) {
  collectionDocumentSet(collectionID: $collectionID, key: $key, data: $data) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation CollectionDocumentDelete($id: ID!) {
  collectionDocumentDelete(id: $id) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation CollectionDocumentTagAdd($id: ID!, $tag: TagInput!) {
  collectionDocumentTagAdd(id: $id, tag: $tag) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

mutation CollectionDocumentTagDelete($id: ID!, $tag_key: String!) {
  collectionDocumentTagDelete(id: $id, key: $tag_key) {
    __typename
    ... on CollectionDocument {
      ...CollectionDocumentReference
    }
  }
}

query CollectionDocuments(
  $collectionID: ID!
  $tag: TagInput
  $after: ID
  $first: Int
) {
  collection(id: $collectionID) {
    __typename
    ... on Collection {
      id
      key
      documents(after: $after, first: $first, tag: $tag) {
        edges {
          node {
            __typename
            ... on CollectionDocument {
              ...CollectionDocumentReference
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}

mutation CollectionFile($collectionID: ID!, $key: ID!) {
  collectionFileCreate(collectionID: $collectionID, key: $key) {
    __typename
    ... on CollectionFile {
      ...CollectionFileReference
    }
  }
}

mutation collectionFileDelete($id: ID!) {
  collectionFileDelete(id: $id) {
    __typename
    ... on CollectionFile {
      ...CollectionFileReference
    }
  }
}

mutation collectionFiles(
  $organizationID: ID!
  $key: ID!
  $tag: TagInput
  $after: ID
  $first: Int
) {
  collectionCreate(organizationID: $organizationID, key: $key) {
    __typename
    ... on Collection {
      id
      key
      files(after: $after, first: $first, tag: $tag) {
        edges {
          node {
            __typename
            ... on CollectionFile {
              ...CollectionFileReference
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}

mutation collectionFileTagAdd($id: ID!, $tag: TagInput!) {
  collectionFileTagAdd(id: $id, tag: $tag) {
    __typename
    ... on CollectionFile {
      ...CollectionFileReference
    }
  }
}

mutation collectionFileTagDelete($id: ID!, $tag_key: String!) {
  collectionFileTagDelete(id: $id, key: $tag_key) {
    __typename
    ... on CollectionFile {
      ...CollectionFileReference
    }
  }
}
